from tkinter import *
import sys,pygame,random
from pygame.locals import *
import os
from snakem import snake, main
from TheProgram import save
from intento3lol import dersim
from matri import matri
from testlocos import tests

def herramientas():
    raiz=Tk()#creación de ventana
    raiz.title("Moni-カ")
    raiz.resizable(0,0)
    raiz.iconbitmap("Recursos/Grafico/Monika2.ico")
    raiz.geometry("1280x720+10+10")
    raiz.config(bg="black")
    raiz.config(bd=1)
    raiz.config(cursor="heart")

    framef=Frame(raiz)
    framef.pack()
    framef.config(bg="#303030")
    framef.config(width="1280",height="720")
    framef.config(bd=1)
    framef.config(cursor="arrow")

    frame1=Frame(raiz)
    frame1.place(x=0, y=0)
    frame1.config(bg="#303030")
    frame1.config(width="1280",height="720")
    frame1.config(bd=1)
    frame1.config(cursor="arrow")

    label1=Label(frame1, text="Order Pickers")
    label1.grid(row=0, column=0, sticky="nsew", pady=1, padx=1)
    label1.config(fg="white")
    label1.config(bg="#303030")
    label1.config(font=("Downlink",20))

    frameline=Frame(frame1)
    frameline.grid(row=1, column=0, sticky="nsew", pady=1, padx=50)
    frameline.config(bg="white")
    frameline.config(width="1180", height="10")

    frame2=Frame(frame1)
    frame2.grid(row=3, column=0, sticky="nsew", pady=20, padx=50)
    frame2.config(bg="black")
    frame2.config(width="1180",height="600")
    frame2.config(bd=1)

    # framem=Frame(frame2)
    # framem.grid(row=0, column=0, sticky="nsew", pady=0, padx=0)
    # framem.config(bg="black")
    # framem.config(width="590",height="35")
    # labelm=Label(framem, text="Matemáticas")
    # labelm.place(x=0, y=0)
    # labelm.config(fg="white")
    # labelm.config(bg="black")
    # labelm.config(font=("Aller",20))

    # framee=Frame(frame2)
    # framee.grid(row=0, column=1, sticky="nsew", pady=0, padx=0)
    # framee.config(bg="black")
    # framee.config(width="590",height="35")
    # labele=Label(framee, text="Extras")
    # labele.place(x=0, y=0)
    # labele.config(fg="white")
    # labele.config(bg="black")
    # labele.config(font=("Aller",20))

    # framecl=Frame(frame2)
    # framecl.grid(row=1, column=0, sticky="nsew", pady=0, padx=0, columnspan=2)
    # framecl.config(bg="#404040")
    # framecl.config(width="1180",height="565")

    # cl=Frame(framecl)
    # cl.grid(row=0, column=0, sticky="nsew", pady=0, padx=0)
    # cl.config(bg="#404040")
    # cl.config(width="1180",height="565")

    # cl1=Frame(cl)
    # cl1.grid(row=0, column=0, sticky="nsew", pady=5, padx=20)
    # cl1.config(bg="#404040")
    # cl1.config(width="295",height="565")

    # bm1=Button(cl1, text="Deriv",command=dersim)
    # bm1.grid(row=0, column=0, sticky="nsew", pady=1, padx=1)
    # bm1.config(width="5",height="2")
    # bm1.config(bg="#0da5c6", bd=0)
    # bm1.config(fg="white")
    # bm1.config(font=("Verdana", 15), justify="center")

    # bm2=Button(cl1, text="Matri",command=matri)
    # bm2.grid(row=0, column=1, sticky="nsew", pady=1, padx=10, columnspan=2)
    # bm2.config(width="10",height="2")
    # bm2.config(bg="#7433a7", bd=0)
    # bm2.config(fg="white")
    # bm2.config(font=("Verdana", 15), justify="center")

    # bm3=Button(cl1, text="Tests",command=tests)
    # bm3.grid(row=1, column=0, sticky="nsew", pady=10, padx=1, columnspan=2)
    # bm3.config(width="10",height="2")
    # bm3.config(bg="#f1c36d", bd=0)
    # bm3.config(fg="white")
    # bm3.config(font=("Verdana", 15), justify="center")

    # bm4=Button(cl1, text="Las")
    # bm4.grid(row=1, column=2, sticky="nsew", pady=10, padx=10)
    # bm4.config(width="5",height="2")
    # bm4.config(bg="#7652f2", bd=0)
    # bm4.config(fg="white")
    # bm4.config(font=("Verdana", 15), justify="center")

    # bm5=Button(cl1, text="Cosas")
    # bm5.grid(row=2, column=0, sticky="nsew", pady=1, padx=1)
    # bm5.config(width="5",height="2")
    # bm5.config(bg="#2bd9c2", bd=0)
    # bm5.config(fg="white")
    # bm5.config(font=("Verdana", 15), justify="center")

    # bm6=Button(cl1, text="Locas")
    # bm6.grid(row=2, column=1, sticky="nsew", pady=1, padx=10, columnspan=2)
    # bm6.config(width="10",height="2")
    # bm6.config(bg="#f2519d", bd=0)
    # bm6.config(fg="white")
    # bm6.config(font=("Verdana", 15), justify="center")

    # bm7=Button(cl1, text="Que")
    # bm7.grid(row=3, column=0, sticky="nsew", pady=10, padx=1, columnspan=2)
    # bm7.config(width="10",height="2")
    # bm7.config(bg="#f3da5c", bd=0)
    # bm7.config(fg="white")
    # bm7.config(font=("Verdana", 15), justify="center")

    # bm8=Button(cl1, text="Se")
    # bm8.grid(row=3, column=2, sticky="nsew", pady=10, padx=10)
    # bm8.config(width="5",height="2")
    # bm8.config(bg="#e84c3d", bd=0)
    # bm8.config(fg="white")
    # bm8.config(font=("Verdana", 15), justify="center")

    # bm9=Button(cl1, text="Supone")
    # bm9.grid(row=4, column=0, sticky="nsw", pady=1, padx=25, columnspan=3)
    # bm9.config(width="10",height="4")
    # bm9.config(bg="white", bd=0)
    # bm9.config(fg="black")
    # bm9.config(font=("Verdana", 15), justify="center")


    # cl2=Frame(cl)
    # cl2.grid(row=0, column=1, sticky="nsew", pady=5, padx=20)
    # cl2.config(bg="#404040")
    # cl2.config(width="295",height="565")

    # bm1=Button(cl2, text="M\no\nn\ni\n-\nk")
    # bm1.grid(row=0, column=0, sticky="nsew", pady=1, padx=5, rowspan=2)
    # bm1.config(width="5",height="5")
    # bm1.config(bg="#d80100", bd=0)
    # bm1.config(fg="white")
    # bm1.config(font=("Verdana", 15), justify="center")

    # bm2=Button(cl2, text="Va")
    # bm2.grid(row=0, column=1, sticky="nsew", pady=1, padx=5)
    # bm2.config(width="5",height="2")
    # bm2.config(bg="#e84c3d", bd=0)
    # bm2.config(fg="white")
    # bm2.config(font=("Verdana", 15), justify="center")

    # bm3=Button(cl2, text="A")
    # bm3.grid(row=0, column=2, sticky="nsew", pady=1, padx=5)
    # bm3.config(width="5",height="2")
    # bm3.config(bg="black", bd=0)
    # bm3.config(fg="white")
    # bm3.config(font=("Verdana", 15), justify="center")

    # bm4=Button(cl2, text="Hacer")
    # bm4.grid(row=1, column=1, sticky="nsew", pady=10, padx=5, columnspan=2)
    # bm4.config(width="10",height="2")
    # bm4.config(bg="#f2519d", bd=0)
    # bm4.config(fg="white")
    # bm4.config(font=("Verdana", 15), justify="center")

    # bm5=Button(cl2, text="Cuando")
    # bm5.grid(row=2, column=0, sticky="nsew", pady=10, padx=5, columnspan=3)
    # bm5.config(width="15",height="2")
    # bm5.config(bg="#cd4352", bd=0)
    # bm5.config(fg="white")
    # bm5.config(font=("Verdana", 15), justify="center")

    # bm6=Button(cl2, text="Ya")
    # bm6.grid(row=3, column=0, sticky="nsew", pady=1, padx=5)
    # bm6.config(width="5",height="2")
    # bm6.config(bg="#2bd9c2", bd=0)
    # bm6.config(fg="white")
    # bm6.config(font=("Verdana", 15), justify="center")

    # bm7=Button(cl2, text="Esté")
    # bm7.grid(row=3, column=1, sticky="nsew", pady=1, padx=5, columnspan=2)
    # bm7.config(width="10",height="2")
    # bm7.config(bg="#f1c36d", bd=0)
    # bm7.config(fg="white")
    # bm7.config(font=("Verdana", 15), justify="center")

    # bm8=Button(cl2, text="Terminada")
    # bm8.grid(row=4, column=0, sticky="nsw", pady=10, padx=30, columnspan=3)
    # bm8.config(width="10",height="4")
    # bm8.config(bg="#0457cd", bd=0)
    # bm8.config(fg="white")
    # bm8.config(font=("Verdana", 15), justify="center")

    # cl3=Frame(cl)
    # cl3.grid(row=0, column=2, sticky="nsew", pady=5, padx=20)
    # cl3.config(bg="#404040")
    # cl3.config(width="295",height="565")

    # bm1=Button(cl3, text="El")
    # bm1.grid(row=0, column=0, sticky="nsew", pady=1, padx=1)
    # bm1.config(width="5",height="2")
    # bm1.config(bg="#73264a", bd=0)
    # bm1.config(fg="white")
    # bm1.config(font=("Verdana", 15), justify="center")

    # bm2=Button(cl3, text="Único")
    # bm2.grid(row=0, column=1, sticky="nsew", pady=1, padx=10, columnspan=2)
    # bm2.config(width="10",height="2")
    # bm2.config(bg="#6f38a0", bd=0)
    # bm2.config(fg="white")
    # bm2.config(font=("Verdana", 15), justify="center")

    # bm3=Button(cl3, text="Funcional")
    # bm3.grid(row=1, column=0, sticky="nsew", pady=10, padx=1, columnspan=2)
    # bm3.config(width="10",height="2")
    # bm3.config(bg="#f2519d", bd=0)
    # bm3.config(fg="white")
    # bm3.config(font=("Verdana", 15), justify="center")

    # bm4=Button(cl3, text="Hasta")
    # bm4.grid(row=1, column=2, sticky="nsew", pady=10, padx=10)
    # bm4.config(width="5",height="2")
    # bm4.config(bg="#7652f2", bd=0)
    # bm4.config(fg="white")
    # bm4.config(font=("Verdana", 15), justify="center")

    # bm5=Button(cl3, text="A\nh\no\nr\na")
    # bm5.grid(row=2, column=0, sticky="nsew", pady=1, padx=1, rowspan=2)
    # bm5.config(width="5",height="5")
    # bm5.config(bg="#d80100", bd=0)
    # bm5.config(fg="white")
    # bm5.config(font=("Verdana", 15), justify="center")

    # bm6=Button(cl3, text="Debería")
    # bm6.grid(row=2, column=1, sticky="nsew", pady=1, padx=10, columnspan=2)
    # bm6.config(width="10",height="2")
    # bm6.config(bg="#f3da5c", bd=0)
    # bm6.config(fg="white")
    # bm6.config(font=("Verdana", 15), justify="center")

    # bm7=Button(cl3, text="Ser")
    # bm7.grid(row=3, column=2, sticky="nsew", pady=10, padx=10)
    # bm7.config(width="5",height="2")
    # bm7.config(bg="#e84c3d", bd=0)
    # bm7.config(fg="white")
    # bm7.config(font=("Verdana", 15), justify="center")

    # #Snake-------------------------------------------------------------------------
    
    #     #main()
    # #Snake-----------------------------------------------------------------------------------------

    # bm8=Button(cl3, text="Este\n (Snake)", command=snake)
    # bm8.grid(row=4, column=0, sticky="nsw", pady=10, padx=30, columnspan=3)
    # bm8.config(width="10",height="4")
    # bm8.config(bg="#04b7d8", bd=0)
    # bm8.config(fg="white")
    # bm8.config(font=("Verdana", 15), justify="center")

    # cl4=Frame(cl)
    # cl4.grid(row=0, column=3, sticky="nsew", pady=5, padx=20)
    # cl4.config(bg="#404040")
    # cl4.config(width="295",height="565")

    # bm1=Button(cl4, text="\nP\ne\nr\no")
    # bm1.grid(row=0, column=0, sticky="nsew", pady=1, padx=10, rowspan=2)
    # bm1.config(width="5",height="5")
    # bm1.config(bg="#d80100", bd=0)
    # bm1.config(fg="white")
    # bm1.config(font=("Verdana", 15), justify="center")

    # bm2=Button(cl4, text="También")
    # bm2.grid(row=0, column=1, sticky="nsew", pady=1, padx=1, columnspan=2)
    # bm2.config(width="10",height="2")
    # bm2.config(bg="#02ada7", bd=0)
    # bm2.config(fg="white")
    # bm2.config(font=("Verdana", 15), justify="center")

    # bm3=Button(cl4, text="Hice")
    # bm3.grid(row=2, column=0, sticky="nsew", pady=10, padx=10)
    # bm3.config(width="5",height="2")
    # bm3.config(bg="#e84c3d", bd=0)
    # bm3.config(fg="white")
    # bm3.config(font=("Verdana", 15), justify="center")

    # bm4=Button(cl4, text="Que")
    # bm4.grid(row=2, column=1, sticky="nsew", pady=10, padx=1)
    # bm4.config(width="5",height="2")
    # bm4.config(bg="#00856a", bd=0)
    # bm4.config(fg="white")
    # bm4.config(font=("Verdana", 15), justify="center")

    # bm5=Button(cl4, text="Funcionara")
    # bm5.grid(row=3, column=0, sticky="nsew", pady=1, padx=10, columnspan=2)
    # bm5.config(width="10",height="2")
    # bm5.config(bg="#f2519d", bd=0)
    # bm5.config(fg="white")
    # bm5.config(font=("Verdana", 15), justify="center")

    # bm6=Button(cl4, text="Este\n (Salva\n vidas)", command=save)
    # bm6.grid(row=4, column=0, sticky="nsw", pady=10, padx=30, columnspan=3)
    # bm6.config(width="10",height="4")
    # bm6.config(bg="#b069cf", bd=0)
    # bm6.config(fg="white")
    # bm6.config(font=("Verdana", 15), justify="center")

    raiz.mainloop()